name: StarTrekCardMaker CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        configuration: [Debug, Release]
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Checkout StarTrekCardMaker
      uses: actions/checkout@v2
    - name: Build StarTrekCardMaker.sln
      run: dotnet build --configuration ${{ matrix.configuration }} ./src/StarTrekCardMaker.sln
