name: CI Build

env:
  BuildDir: ./bld
  ScriptDir: ./scripts

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: pwsh

jobs:
  ci_build_windows:
    name: CI Windows Build
    runs-on: windows-latest
    strategy:
      matrix:
        target: [Portable, Windows]
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Get 7zip
      working-directory: ./
      run: |
        mkdir ${{ env.BuildDir }}
        curl https://www.7-zip.org/a/7zr.exe -o ${{ env.BuildDir }}/7zr.exe 
        curl https://www.7-zip.org/a/7z1900-extra.7z -o ${{ env.BuildDir }}/7z1900-extra.7z
        ${{ env.BuildDir }}/7zr.exe e ${{ env.BuildDir }}/7z1900-extra.7z -obld 7za.exe

    - name: Build ${{ matrix.target }}
      run: ${{ env.ScriptDir }}/Build${{ matrix.target }}.ps1

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: StarTrekCardMaker.${{ matrix.target }}
        path: ${{ env.BuildDir }}/StarTrekCardMaker.${{ matrix.target }}.zip
    
  ci_build_linux:
    name: CI Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [Linux]
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build ${{ matrix.target }}
      run: ${{ env.ScriptDir }}/Build${{ matrix.target }}.ps1

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: StarTrekCardMaker.${{ matrix.target }}
        path: ${{ env.BuildDir }}/StarTrekCardMaker.${{ matrix.target }}.tar.gz
  
  ci_build_macos:
    name: CI MacOS Build
    runs-on: macOS-latest
    strategy:
      matrix:
        target: [MacOS]
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build ${{ matrix.target }}
      run: ${{ env.ScriptDir }}/Build${{ matrix.target }}.ps1

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: StarTrekCardMaker.${{ matrix.target }}
        path: ${{ env.BuildDir }}/StarTrekCardMaker.${{ matrix.target }}.tar.gz
