name: Pull Request Validation

env:
  SolutionFile: ./src/StarTrekCardMaker.sln
  BuildDir: ./src/StarTrekCardMaker/bin

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Solution
      run: dotnet build --configuration ${{ matrix.configuration }} ${{ env.SolutionFile }}

    - name: Test Solution
      run: dotnet test --configuration ${{ matrix.configuration }} --no-build ${{ env.SolutionFile }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      name:  ${{ matrix.configuration }}-Build
      path: ${{ env.BuildDir }}/${{ matrix.configuration }}/netcoreapp3.1
